[tool.poetry]
name = "valueserp"
version = "0.1.2"
description = "Client library for VALUE SERP: https://www.valueserp.com/"
authors = ["Joe Joiner <2454320+joejoinerr@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = ">=3.8"
requests = "^2.27.1"
loguru = "^0.6.0"
requests-toolbelt = "^0.9.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
