[tool.poetry]
name = "valueserp"
version = "0.2.0"
description = "Client library for VALUE SERP: https://www.valueserp.com/"
authors = ["Joe Joiner <2454320+joejoinerr@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<4"
requests = "^2.28.1"
loguru = "^0.6.0"
requests-toolbelt = "^0.9.1"
Sphinx = "^5.0.2"
sphinx-rtd-theme = "^1.0.0"
httpx = {extras = ["http2"], version = "^0.27.0"}

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
pytest-asyncio = "^0.23.7"
pytest = "^8.2.1"
respx = "^0.21.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode = "auto"
